// 国家/地区/省市数据 - 主要覆盖中国、美国、澳大利亚、欧洲等
export interface RegionOption {
  value: string
  label: string
  children?: RegionOption[]
}

const regionData: RegionOption[] = [
  {
    value: 'CN',
    label: '中国',
    children: [
      {
        value: 'beijing',
        label: '北京市',
        children: [
          { value: 'dongcheng', label: '东城区' },
          { value: 'xicheng', label: '西城区' },
          { value: 'chaoyang', label: '朝阳区' },
          { value: 'fengtai', label: '丰台区' },
          { value: 'shijingshan', label: '石景山区' },
          { value: 'haidian', label: '海淀区' },
          { value: 'mentougou', label: '门头沟区' },
          { value: 'fangshan', label: '房山区' },
          { value: 'tongzhou', label: '通州区' },
          { value: 'shunyi', label: '顺义区' },
          { value: 'changping', label: '昌平区' },
          { value: 'daxing', label: '大兴区' },
        ],
      },
      {
        value: 'shanghai',
        label: '上海市',
        children: [
          { value: 'huangpu', label: '黄浦区' },
          { value: 'xuhui', label: '徐汇区' },
          { value: 'changning', label: '长宁区' },
          { value: 'jing_an', label: '静安区' },
          { value: 'putuo', label: '普陀区' },
          { value: 'hongkou', label: '虹口区' },
          { value: 'yangpu', label: '杨浦区' },
          { value: 'minhang', label: '闵行区' },
          { value: 'baoshan', label: '宝山区' },
          { value: 'jiading', label: '嘉定区' },
          { value: 'pudong', label: '浦东新区' },
          { value: 'songjiang', label: '松江区' },
        ],
      },
      {
        value: 'guangdong',
        label: '广东省',
        children: [
          { value: 'guangzhou', label: '广州市' },
          { value: 'shenzhen', label: '深圳市' },
          { value: 'zhuhai', label: '珠海市' },
          { value: 'shantou', label: '汕头市' },
          { value: 'foshan', label: '佛山市' },
          { value: 'shaoguan', label: '韶关市' },
          { value: 'zhanjiang', label: '湛江市' },
          { value: 'zhaoqing', label: '肇庆市' },
          { value: 'jiangmen', label: '江门市' },
          { value: 'maoming', label: '茂名市' },
          { value: 'huizhou', label: '惠州市' },
          { value: 'meizhou', label: '梅州市' },
          { value: 'shanwei', label: '汕尾市' },
          { value: 'dongguan', label: '东莞市' },
          { value: 'zhongshan', label: '中山市' },
        ],
      },
      {
        value: 'zhejiang',
        label: '浙江省',
        children: [
          { value: 'hangzhou', label: '杭州市' },
          { value: 'ningbo', label: '宁波市' },
          { value: 'wenzhou', label: '温州市' },
          { value: 'jiaxing', label: '嘉兴市' },
          { value: 'huzhou', label: '湖州市' },
          { value: 'shaoxing', label: '绍兴市' },
          { value: 'jinhua', label: '金华市' },
          { value: 'quzhou', label: '衢州市' },
          { value: 'zhoushan', label: '舟山市' },
          { value: 'taizhou', label: '台州市' },
          { value: 'lishui', label: '丽水市' },
        ],
      },
      {
        value: 'jiangsu',
        label: '江苏省',
        children: [
          { value: 'nanjing', label: '南京市' },
          { value: 'wuxi', label: '无锡市' },
          { value: 'xuzhou', label: '徐州市' },
          { value: 'changzhou', label: '常州市' },
          { value: 'suzhou', label: '苏州市' },
          { value: 'nantong', label: '南通市' },
          { value: 'lianyungang', label: '连云港市' },
          { value: 'huaian', label: '淮安市' },
          { value: 'yancheng', label: '盐城市' },
          { value: 'yangzhou', label: '扬州市' },
          { value: 'zhenjiang', label: '镇江市' },
          { value: 'taizhou_js', label: '泰州市' },
          { value: 'suqian', label: '宿迁市' },
        ],
      },
      {
        value: 'shandong',
        label: '山东省',
        children: [
          { value: 'jinan', label: '济南市' },
          { value: 'qingdao', label: '青岛市' },
          { value: 'zibo', label: '淄博市' },
          { value: 'zaozhuang', label: '枣庄市' },
          { value: 'dongying', label: '东营市' },
          { value: 'yantai', label: '烟台市' },
          { value: 'weifang', label: '潍坊市' },
          { value: 'jining', label: '济宁市' },
          { value: 'taian', label: '泰安市' },
          { value: 'weihai', label: '威海市' },
          { value: 'rizhao', label: '日照市' },
          { value: 'linyi', label: '临沂市' },
          { value: 'dezhou', label: '德州市' },
          { value: 'liaocheng', label: '聊城市' },
          { value: 'binzhou', label: '滨州市' },
          { value: 'heze', label: '菏泽市' },
        ],
      },
      {
        value: 'sichuan',
        label: '四川省',
        children: [
          { value: 'chengdu', label: '成都市' },
          { value: 'zigong', label: '自贡市' },
          { value: 'panzhihua', label: '攀枝花市' },
          { value: 'luzhou', label: '泸州市' },
          { value: 'deyang', label: '德阳市' },
          { value: 'mianyang', label: '绵阳市' },
          { value: 'guangyuan', label: '广元市' },
          { value: 'suining', label: '遂宁市' },
          { value: 'neijiang', label: '内江市' },
          { value: 'leshan', label: '乐山市' },
          { value: 'nanchong', label: '南充市' },
          { value: 'meishan', label: '眉山市' },
          { value: 'yibin', label: '宜宾市' },
          { value: 'guangan', label: '广安市' },
          { value: 'dazhou', label: '达州市' },
        ],
      },
      {
        value: 'hubei',
        label: '湖北省',
        children: [
          { value: 'wuhan', label: '武汉市' },
          { value: 'huangshi', label: '黄石市' },
          { value: 'shiyan', label: '十堰市' },
          { value: 'yichang', label: '宜昌市' },
          { value: 'xiangyang', label: '襄阳市' },
          { value: 'ezhou', label: '鄂州市' },
          { value: 'jingmen', label: '荆门市' },
          { value: 'xiaogan', label: '孝感市' },
          { value: 'jingzhou', label: '荆州市' },
          { value: 'huanggang', label: '黄冈市' },
          { value: 'xianning', label: '咸宁市' },
          { value: 'suizhou', label: '随州市' },
        ],
      },
      {
        value: 'hunan',
        label: '湖南省',
        children: [
          { value: 'changsha', label: '长沙市' },
          { value: 'zhuzhou', label: '株洲市' },
          { value: 'xiangtan', label: '湘潭市' },
          { value: 'hengyang', label: '衡阳市' },
          { value: 'shaoyang', label: '邵阳市' },
          { value: 'yueyang', label: '岳阳市' },
          { value: 'changde', label: '常德市' },
          { value: 'zhangjiajie', label: '张家界市' },
          { value: 'yiyang', label: '益阳市' },
          { value: 'chenzhou', label: '郴州市' },
          { value: 'yongzhou', label: '永州市' },
          { value: 'huaihua', label: '怀化市' },
          { value: 'loudi', label: '娄底市' },
        ],
      },
      {
        value: 'fujian',
        label: '福建省',
        children: [
          { value: 'fuzhou', label: '福州市' },
          { value: 'xiamen', label: '厦门市' },
          { value: 'putian', label: '莆田市' },
          { value: 'sanming', label: '三明市' },
          { value: 'quanzhou', label: '泉州市' },
          { value: 'zhangzhou', label: '漳州市' },
          { value: 'nanping', label: '南平市' },
          { value: 'longyan', label: '龙岩市' },
          { value: 'ningde', label: '宁德市' },
        ],
      },
      {
        value: 'hebei',
        label: '河北省',
        children: [
          { value: 'shijiazhuang', label: '石家庄市' },
          { value: 'tangshan', label: '唐山市' },
          { value: 'qinhuangdao', label: '秦皇岛市' },
          { value: 'handan', label: '邯郸市' },
          { value: 'xingtai', label: '邢台市' },
          { value: 'baoding', label: '保定市' },
          { value: 'zhangjiakou', label: '张家口市' },
          { value: 'chengde', label: '承德市' },
          { value: 'cangzhou', label: '沧州市' },
          { value: 'langfang', label: '廊坊市' },
          { value: 'hengshui', label: '衡水市' },
        ],
      },
      {
        value: 'henan',
        label: '河南省',
        children: [
          { value: 'zhengzhou', label: '郑州市' },
          { value: 'kaifeng', label: '开封市' },
          { value: 'luoyang', label: '洛阳市' },
          { value: 'pingdingshan', label: '平顶山市' },
          { value: 'anyang', label: '安阳市' },
          { value: 'hebi', label: '鹤壁市' },
          { value: 'xinxiang', label: '新乡市' },
          { value: 'jiaozuo', label: '焦作市' },
          { value: 'puyang', label: '濮阳市' },
          { value: 'xuchang', label: '许昌市' },
          { value: 'luohe', label: '漯河市' },
          { value: 'sanmenxia', label: '三门峡市' },
          { value: 'nanyang', label: '南阳市' },
          { value: 'shangqiu', label: '商丘市' },
          { value: 'xinyang', label: '信阳市' },
        ],
      },
      {
        value: 'liaoning',
        label: '辽宁省',
        children: [
          { value: 'shenyang', label: '沈阳市' },
          { value: 'dalian', label: '大连市' },
          { value: 'anshan', label: '鞍山市' },
          { value: 'fushun', label: '抚顺市' },
          { value: 'benxi', label: '本溪市' },
          { value: 'dandong', label: '丹东市' },
          { value: 'jinzhou', label: '锦州市' },
          { value: 'yingkou', label: '营口市' },
          { value: 'fuxin', label: '阜新市' },
          { value: 'liaoyang', label: '辽阳市' },
          { value: 'panjin', label: '盘锦市' },
          { value: 'tieling', label: '铁岭市' },
          { value: 'chaoyang', label: '朝阳市' },
          { value: 'huludao', label: '葫芦岛市' },
        ],
      },
      {
        value: 'jilin',
        label: '吉林省',
        children: [
          { value: 'changchun', label: '长春市' },
          { value: 'jilin', label: '吉林市' },
          { value: 'siping', label: '四平市' },
          { value: 'liaoyuan', label: '辽源市' },
          { value: 'tonghua', label: '通化市' },
          { value: 'baishan', label: '白山市' },
          { value: 'songyuan', label: '松原市' },
          { value: 'baicheng', label: '白城市' },
        ],
      },
      {
        value: 'heilongjiang',
        label: '黑龙江省',
        children: [
          { value: 'haerbin', label: '哈尔滨市' },
          { value: 'qiqihar', label: '齐齐哈尔市' },
          { value: 'jixi', label: '鸡西市' },
          { value: 'hegang', label: '鹤岗市' },
          { value: 'shuangyashan', label: '双鸭山市' },
          { value: 'daqing', label: '大庆市' },
          { value: 'yichun', label: '伊春市' },
          { value: 'jiamusi', label: '佳木斯市' },
          { value: 'qitaihe', label: '七台河市' },
          { value: 'mudanjiang', label: '牡丹江市' },
          { value: 'heihe', label: '黑河市' },
          { value: 'suihua', label: '绥化市' },
        ],
      },
      {
        value: 'anhui',
        label: '安徽省',
        children: [
          { value: 'hefei', label: '合肥市' },
          { value: 'wuhu', label: '芜湖市' },
          { value: 'bengbu', label: '蚌埠市' },
          { value: 'huainan', label: '淮南市' },
          { value: 'maanshan', label: '马鞍山市' },
          { value: 'huaibei', label: '淮北市' },
          { value: 'tongling', label: '铜陵市' },
          { value: 'anqing', label: '安庆市' },
          { value: 'huangshan', label: '黄山市' },
          { value: 'chuzhou', label: '滁州市' },
          { value: 'fuyang', label: '阜阳市' },
          { value: 'suzhou_ah', label: '宿州市' },
          { value: 'luan', label: '六安市' },
          { value: 'bozhou', label: '亳州市' },
          { value: 'chizhou', label: '池州市' },
          { value: 'xuancheng', label: '宣城市' },
        ],
      },
      {
        value: 'jiangxi',
        label: '江西省',
        children: [
          { value: 'nanchang', label: '南昌市' },
          { value: 'jingdezhen', label: '景德镇市' },
          { value: 'pingxiang', label: '萍乡市' },
          { value: 'jiujiang', label: '九江市' },
          { value: 'xinyu', label: '新余市' },
          { value: 'yingtan', label: '鹰潭市' },
          { value: 'ganzhou', label: '赣州市' },
          { value: 'jian', label: '吉安市' },
          { value: 'yichun', label: '宜春市' },
          { value: 'fuzhou_jx', label: '抚州市' },
          { value: 'shangrao', label: '上饶市' },
        ],
      },
      {
        value: 'shanxi',
        label: '山西省',
        children: [
          { value: 'taiyuan', label: '太原市' },
          { value: 'datong', label: '大同市' },
          { value: 'yangquan', label: '阳泉市' },
          { value: 'changzhi', label: '长治市' },
          { value: 'jincheng', label: '晋城市' },
          { value: 'shuozhou', label: '朔州市' },
          { value: 'jinzhong', label: '晋中市' },
          { value: 'yuncheng', label: '运城市' },
          { value: 'xinzhou', label: '忻州市' },
          { value: 'linfen', label: '临汾市' },
          { value: 'lvliang', label: '吕梁市' },
        ],
      },
      {
        value: 'shaanxi',
        label: '陕西省',
        children: [
          { value: 'xian', label: '西安市' },
          { value: 'tongchuan', label: '铜川市' },
          { value: 'baoji', label: '宝鸡市' },
          { value: 'xianyang', label: '咸阳市' },
          { value: 'weinan', label: '渭南市' },
          { value: 'yanan', label: '延安市' },
          { value: 'hanzhong', label: '汉中市' },
          { value: 'yulin', label: '榆林市' },
          { value: 'ankang', label: '安康市' },
          { value: 'shangluo', label: '商洛市' },
        ],
      },
      {
        value: 'gansu',
        label: '甘肃省',
        children: [
          { value: 'lanzhou', label: '兰州市' },
          { value: 'jiayuguan', label: '嘉峪关市' },
          { value: 'jinchang', label: '金昌市' },
          { value: 'baiyin', label: '白银市' },
          { value: 'tianshui', label: '天水市' },
          { value: 'wuwei', label: '武威市' },
          { value: 'zhangye', label: '张掖市' },
          { value: 'pingliang', label: '平凉市' },
          { value: 'jiuquan', label: '酒泉市' },
          { value: 'qingyang', label: '庆阳市' },
          { value: 'dingxi', label: '定西市' },
          { value: 'longnan', label: '陇南市' },
        ],
      },
      {
        value: 'qinghai',
        label: '青海省',
        children: [
          { value: 'xining', label: '西宁市' },
          { value: 'haidong', label: '海东市' },
        ],
      },
      {
        value: 'hainan',
        label: '海南省',
        children: [
          { value: 'haikou', label: '海口市' },
          { value: 'sanya', label: '三亚市' },
          { value: 'sansha', label: '三沙市' },
          { value: 'danzhou', label: '儋州市' },
        ],
      },
      {
        value: 'taiwan',
        label: '台湾省',
        children: [
          { value: 'taipei', label: '台北市' },
          { value: 'kaohsiung', label: '高雄市' },
          { value: 'taichung', label: '台中市' },
          { value: 'tainan', label: '台南市' },
          { value: 'new_taipei', label: '新北市' },
          { value: 'taoyuan', label: '桃园市' },
        ],
      },
      {
        value: 'neimenggu',
        label: '内蒙古自治区',
        children: [
          { value: 'hohhot', label: '呼和浩特市' },
          { value: 'baotou', label: '包头市' },
          { value: 'wuhai', label: '乌海市' },
          { value: 'chifeng', label: '赤峰市' },
          { value: 'tongliao', label: '通辽市' },
          { value: 'ordos', label: '鄂尔多斯市' },
          { value: 'hulunbuir', label: '呼伦贝尔市' },
          { value: 'bayannur', label: '巴彦淖尔市' },
          { value: 'ulanchab', label: '乌兰察布市' },
        ],
      },
      {
        value: 'guangxi',
        label: '广西壮族自治区',
        children: [
          { value: 'nanning', label: '南宁市' },
          { value: 'liuzhou', label: '柳州市' },
          { value: 'guilin', label: '桂林市' },
          { value: 'wuzhou', label: '梧州市' },
          { value: 'beihai', label: '北海市' },
          { value: 'fangchenggang', label: '防城港市' },
          { value: 'qinzhou', label: '钦州市' },
          { value: 'guigang', label: '贵港市' },
          { value: 'yulin', label: '玉林市' },
          { value: 'baise', label: '百色市' },
          { value: 'hezhou', label: '贺州市' },
          { value: 'hechi', label: '河池市' },
          { value: 'laibin', label: '来宾市' },
          { value: 'chongzuo', label: '崇左市' },
        ],
      },
      {
        value: 'xizang',
        label: '西藏自治区',
        children: [
          { value: 'lhasa', label: '拉萨市' },
          { value: 'rikaze', label: '日喀则市' },
          { value: 'changdu', label: '昌都市' },
          { value: 'linzhi', label: '林芝市' },
          { value: 'shannan', label: '山南市' },
          { value: 'naqu', label: '那曲市' },
        ],
      },
      {
        value: 'ningxia',
        label: '宁夏回族自治区',
        children: [
          { value: 'yinchuan', label: '银川市' },
          { value: 'shizuishan', label: '石嘴山市' },
          { value: 'wuzhong', label: '吴忠市' },
          { value: 'guyuan', label: '固原市' },
          { value: 'zhongwei', label: '中卫市' },
        ],
      },
      {
        value: 'xinjiang',
        label: '新疆维吾尔自治区',
        children: [
          { value: 'urumqi', label: '乌鲁木齐市' },
          { value: 'karamay', label: '克拉玛依市' },
          { value: 'turpan', label: '吐鲁番市' },
          { value: 'hami', label: '哈密市' },
        ],
      },
      {
        value: 'hongkong',
        label: '香港特别行政区',
        children: [
          { value: 'central', label: '中西区' },
          { value: 'wan_chai', label: '湾仔区' },
          { value: 'eastern', label: '东区' },
          { value: 'southern', label: '南区' },
          { value: 'yau_tsim_mong', label: '油尖旺区' },
          { value: 'sham_shui_po', label: '深水埗区' },
          { value: 'kowloon_city', label: '九龙城区' },
          { value: 'wong_tai_sin', label: '黄大仙区' },
          { value: 'kwun_tong', label: '观塘区' },
        ],
      },
      {
        value: 'macau',
        label: '澳门特别行政区',
        children: [
          { value: 'nossa_senhora_de_fatima', label: '花地玛堂区' },
          { value: 'santo_antonio', label: '花王堂区' },
          { value: 'sao_lazaro', label: '望德堂区' },
          { value: 'se', label: '大堂区' },
          { value: 'sao_lourenco', label: '风顺堂区' },
        ],
      },
    ],
  },
  {
    value: 'US',
    label: 'United States',
    children: [
      {
        value: 'california',
        label: 'California',
        children: [
          { value: 'los_angeles', label: 'Los Angeles' },
          { value: 'san_francisco', label: 'San Francisco' },
          { value: 'san_diego', label: 'San Diego' },
          { value: 'san_jose', label: 'San Jose' },
        ],
      },
      {
        value: 'new_york',
        label: 'New York',
        children: [
          { value: 'new_york_city', label: 'New York City' },
          { value: 'buffalo', label: 'Buffalo' },
          { value: 'albany', label: 'Albany' },
        ],
      },
      {
        value: 'texas',
        label: 'Texas',
        children: [
          { value: 'houston', label: 'Houston' },
          { value: 'dallas', label: 'Dallas' },
          { value: 'austin', label: 'Austin' },
          { value: 'san_antonio', label: 'San Antonio' },
        ],
      },
      {
        value: 'florida',
        label: 'Florida',
        children: [
          { value: 'miami', label: 'Miami' },
          { value: 'orlando', label: 'Orlando' },
          { value: 'tampa', label: 'Tampa' },
        ],
      },
    ],
  },
  {
    value: 'AU',
    label: 'Australia',
    children: [
      {
        value: 'new_south_wales',
        label: 'New South Wales',
        children: [
          { value: 'sydney', label: 'Sydney' },
          { value: 'newcastle', label: 'Newcastle' },
          { value: 'wollongong', label: 'Wollongong' },
        ],
      },
      {
        value: 'victoria',
        label: 'Victoria',
        children: [
          { value: 'melbourne', label: 'Melbourne' },
          { value: 'geelong', label: 'Geelong' },
        ],
      },
      {
        value: 'queensland',
        label: 'Queensland',
        children: [
          { value: 'brisbane', label: 'Brisbane' },
          { value: 'gold_coast', label: 'Gold Coast' },
          { value: 'cairns', label: 'Cairns' },
        ],
      },
      {
        value: 'western_australia',
        label: 'Western Australia',
        children: [
          { value: 'perth', label: 'Perth' },
        ],
      },
    ],
  },
  {
    value: 'DE',
    label: 'Germany',
    children: [
      {
        value: 'bavaria',
        label: 'Bavaria',
        children: [
          { value: 'munich', label: 'Munich' },
          { value: 'nuremberg', label: 'Nuremberg' },
        ],
      },
      {
        value: 'berlin',
        label: 'Berlin',
        children: [
          { value: 'berlin_city', label: 'Berlin' },
        ],
      },
      {
        value: 'north_rhine_westphalia',
        label: 'North Rhine-Westphalia',
        children: [
          { value: 'cologne', label: 'Cologne' },
          { value: 'dusseldorf', label: 'Düsseldorf' },
        ],
      },
    ],
  },
  {
    value: 'GB',
    label: 'United Kingdom',
    children: [
      {
        value: 'england',
        label: 'England',
        children: [
          { value: 'london', label: 'London' },
          { value: 'manchester', label: 'Manchester' },
          { value: 'birmingham', label: 'Birmingham' },
          { value: 'liverpool', label: 'Liverpool' },
        ],
      },
      {
        value: 'scotland',
        label: 'Scotland',
        children: [
          { value: 'edinburgh', label: 'Edinburgh' },
          { value: 'glasgow', label: 'Glasgow' },
        ],
      },
    ],
  },
  {
    value: 'JP',
    label: 'Japan',
    children: [
      {
        value: 'tokyo',
        label: 'Tokyo',
        children: [
          { value: 'shibuya', label: 'Shibuya' },
          { value: 'shinjuku', label: 'Shinjuku' },
        ],
      },
      {
        value: 'osaka',
        label: 'Osaka',
        children: [
          { value: 'osaka_city', label: 'Osaka City' },
        ],
      },
    ],
  },
  {
    value: 'KR',
    label: 'South Korea',
    children: [
      {
        value: 'seoul',
        label: 'Seoul',
        children: [
          { value: 'gangnam', label: 'Gangnam' },
          { value: 'jongno', label: 'Jongno' },
        ],
      },
      {
        value: 'busan',
        label: 'Busan',
        children: [
          { value: 'haeundae', label: 'Haeundae' },
        ],
      },
    ],
  },
  {
    value: 'SG',
    label: 'Singapore',
    children: [
      {
        value: 'central',
        label: 'Central Region',
        children: [
          { value: 'orchard', label: 'Orchard' },
          { value: 'marina_bay', label: 'Marina Bay' },
        ],
      },
    ],
  },
]

export default regionData
