ALTER TABLE firmware_versions ADD COLUMN IF NOT EXISTS file_sha256 VARCHAR(64) DEFAULT '';
ALTER TABLE firmware_versions ADD COLUMN IF NOT EXISTS uploaded_by BIGINT DEFAULT 0;
ALTER TABLE firmware_versions ADD COLUMN IF NOT EXISTS target_chip VARCHAR(50) DEFAULT '';
ALTER TABLE firmware_versions ADD COLUMN IF NOT EXISTS main_version VARCHAR(50) DEFAULT '';
ALTER TABLE firmware_versions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
