#!/usr/bin/env python3
"""Migration squash: 把 schema.sql + 所有 1..N 迁移合并成新的 baseline schema.sql。

用法（PowerShell）：python tools/squash_migrations.py

副作用：
  1. 生成新的 database/schema.sql（覆盖老文件）
  2. 把 database/migrations/*.sql 全部移到 database/migrations.archive/
  3. 在 database/migrations/ 留一个占位 001_baseline_marker.up.sql（migrator 强制要求 dir 非空）
  4. 打印下一个迁移应使用的版本号
"""
from __future__ import annotations
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB_DIR = ROOT / "database"
MIG_DIR = DB_DIR / "migrations"
ARCHIVE = DB_DIR / "migrations.archive"
SCHEMA = DB_DIR / "schema.sql"
OUT = DB_DIR / "schema.squashed.sql"

# ---------- 1. 读 baseline ----------
base_sql = SCHEMA.read_text(encoding="utf-8")

# ---------- 2. 扫所有迁移文件，按版本号排序（只取 .up.sql 或 无 .up/.down 的 .sql） ----------
files = []
for p in sorted(MIG_DIR.iterdir()):
    if not p.is_file():
        continue
    name = p.name
    m = re.match(r"^(\d+)_(.*)$", name)
    if not m:
        continue
    ver = int(m.group(1))
    # 跳过 .down.sql（squash 不需要回滚）
    if name.endswith(".down.sql"):
        continue
    # 只接受 .up.sql 或 .sql（无后缀标识）
    if not (name.endswith(".up.sql") or name.endswith(".sql")):
        continue
    files.append((ver, p))

files.sort(key=lambda x: (x[0], x[1].name))
max_ver = files[-1][0] if files else 0
print(f">>> 发现 {len(files)} 个 .up.sql / .sql 迁移，最大版本 {max_ver}")

# ---------- 3. 拼接到新 schema ----------
parts = []
parts.append("-- ============================================================\n")
parts.append("-- cs_inv_monitor - Baseline Schema (squashed)\n")
parts.append(f"-- Baseline includes: original schema.sql + migrations 1..{max_ver}\n")
parts.append("-- Generated by: python tools/squash_migrations.py\n")
parts.append("-- ============================================================\n\n")
parts.append(base_sql)
parts.append("\n\n-- ============================================================\n")
parts.append(f"-- SQUASHED MIGRATIONS 1..{max_ver}\n")
parts.append("-- ============================================================\n\n")

for ver, p in files:
    content = p.read_text(encoding="utf-8")
    parts.append(f"-- ---------- Migration {ver}: {p.name} ----------\n")
    parts.append(content.rstrip())
    parts.append("\n\n")

# ---------- 4. 确保 schema_migrations 表存在 + 标记 0..max_ver 已 apply ----------
parts.append("-- ============================================================\n")
parts.append("-- BASELINE MARKER: 标记所有已合并的迁移为已应用\n")
parts.append("-- migrator 启动时会看到这些记录并跳过，不再重复跑 1..%d\n" % max_ver)
parts.append("-- ============================================================\n\n")
parts.append("CREATE TABLE IF NOT EXISTS schema_migrations (\n")
parts.append("    version    BIGINT PRIMARY KEY,\n")
parts.append("    name       VARCHAR(255) NOT NULL,\n")
parts.append("    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n")
parts.append(");\n\n")

# INSERT 0（baseline 占位，migrator 内部有 'INSERT version 0 = baseline_schema' 逻辑）
parts.append("INSERT INTO schema_migrations (version, name)\n")
parts.append("VALUES (0, 'baseline_schema')\n")
parts.append("ON CONFLICT (version) DO NOTHING;\n\n")

# INSERT 1..max_ver
for ver, p in files:
    safe_name = p.name.replace("'", "''")
    parts.append(
        f"INSERT INTO schema_migrations (version, name) VALUES ({ver}, '{safe_name}') "
        "ON CONFLICT (version) DO NOTHING;\n"
    )

parts.append(f"\n-- Next migration version to use: {max_ver + 1:03d}\n")

OUT.write_text("".join(parts), encoding="utf-8")
print(f">>> 生成 {OUT.relative_to(ROOT)}  ({OUT.stat().st_size} bytes)")

# ---------- 5. 替换 schema.sql ----------
backup = DB_DIR / "schema.sql.pre-squash.bak"
shutil.copy2(SCHEMA, backup)
shutil.move(str(OUT), str(SCHEMA))
print(f">>> 老 schema.sql 备份到 {backup.relative_to(ROOT)}")

# ---------- 6. 归档老迁移文件 ----------
if ARCHIVE.exists():
    # 如果 archive 已有文件，加时间戳避免冲突
    import time
    ts = time.strftime("%Y%m%d-%H%M%S")
    ARCHIVE_TS = DB_DIR / f"migrations.archive.{ts}"
    shutil.move(str(ARCHIVE), str(ARCHIVE_TS))
    print(f">>> 旧 archive 重命名为 {ARCHIVE_TS.name}")

ARCHIVE.mkdir(parents=True, exist_ok=True)
moved = 0
for p in list(MIG_DIR.iterdir()):
    if p.is_file():
        shutil.move(str(p), str(ARCHIVE / p.name))
        moved += 1
print(f">>> {moved} 个迁移文件归档到 {ARCHIVE.relative_to(ROOT)}/")

# ---------- 7. 创建占位文件（migrator 强制 dir 非空） ----------
placeholder = MIG_DIR / "001_baseline_marker.up.sql"
placeholder.write_text(
    "-- Placeholder migration.\n"
    "-- The real 1..%d migrations have been squashed into database/schema.sql.\n"
    "-- This file exists only to satisfy the migrator's 'dir must not be empty' check.\n"
    "-- Future migrations should start numbering from %03d.\n"
    "SELECT 1;\n" % (max_ver, max_ver + 1),
    encoding="utf-8",
)
print(f">>> 创建占位文件 {placeholder.name}")
print(f">>> 下一个新迁移应使用版本号 {max_ver + 1:03d}")
print("\n✅ squash 完成。请提交：")
print("   git add database/")
print("   git commit -m 'chore(db): squash migrations 1..%d into baseline schema.sql'" % max_ver)
